-- MySQL Script generated by MySQL Workbench
-- Fri May  3 14:00:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `chassi_veículo` INT NOT NULL,
  `modelo_veiculo` VARCHAR(50) NOT NULL,
  `marca_veiculo` VARCHAR(50) NOT NULL,
  `ano_veiculo` INT(50) NOT NULL,
  `placa_veiculo` VARCHAR(20) NOT NULL,
  `tipo_veiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`chassi_veículo`),
  UNIQUE INDEX `placa_UNIQUE` (`placa_veiculo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `numero_cpf_cliente` INT NOT NULL,
  `nome_cliente` VARCHAR(50) NOT NULL,
  `sobrenome_cliente` VARCHAR(50) NOT NULL,
  `endereço_cliente` VARCHAR(50) NULL,
  `email_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero_cpf_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email_cliente` ASC) VISIBLE,
  UNIQUE INDEX `id_Cliente_UNIQUE` (`numero_cpf_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devolucao` (
  `id_devolucao` INT NOT NULL AUTO_INCREMENT,
  `id_locacao` INT NOT NULL,
  `data_hora_devolucao` DATETIME NOT NULL,
  `danos_devolucao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_devolucao`, `id_locacao`),
  INDEX `id_locacao_idx` (`id_locacao` ASC) VISIBLE,
  CONSTRAINT `id_locacao`
    FOREIGN KEY (`id_locacao`)
    REFERENCES `mydb`.`locacao` (`id_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disponibilidade` (
  `disponivel` INT(1) NOT NULL,
  `indisponivel` INT(1) NOT NULL,
  `chassi_veiculo` INT NOT NULL,
  `id_locacao` INT NOT NULL,
  PRIMARY KEY (`disponivel`, `indisponivel`, `chassi_veiculo`, `id_locacao`),
  INDEX `chassi_veículo_idx` (`chassi_veiculo` ASC) VISIBLE,
  INDEX `id_locacao_idx` (`id_locacao` ASC) VISIBLE,
  CONSTRAINT `chassi_veículo`
    FOREIGN KEY (`chassi_veiculo`)
    REFERENCES `mydb`.`Veiculo` (`chassi_veículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_locacao`
    FOREIGN KEY (`id_locacao`)
    REFERENCES `mydb`.`locacao` (`id_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `id_locacao` INT NOT NULL AUTO_INCREMENT,
  `numero_cpf_cliente` INT NOT NULL,
  `chassi_veiculo` INT NOT NULL,
  `data_inicio_devolucao` DATE NOT NULL,
  `data_termino_devolucao` DATE NOT NULL,
  `valor_total_devolucao` FLOAT NOT NULL,
  PRIMARY KEY (`id_locacao`, `numero_cpf_cliente`, `chassi_veiculo`),
  INDEX `id_cliente_idx` (`numero_cpf_cliente` ASC) VISIBLE,
  INDEX `id_veiículo_idx` (`chassi_veiculo` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`numero_cpf_cliente`)
    REFERENCES `mydb`.`cliente` (`numero_cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veiículo`
    FOREIGN KEY (`chassi_veiculo`)
    REFERENCES `mydb`.`Veiculo` (`chassi_veículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `numero_cpf_cliente` INT NOT NULL,
  `chassi_veiculo` INT NOT NULL,
  `data_inicio_reserva` DATE NOT NULL,
  `data_termino_reserva` DATE NOT NULL,
  PRIMARY KEY (`id_reserva`, `numero_cpf_cliente`, `chassi_veiculo`),
  INDEX `id_cliente_idx` (`numero_cpf_cliente` ASC) VISIBLE,
  INDEX `id_Veículo_idx` (`chassi_veiculo` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`numero_cpf_cliente`)
    REFERENCES `mydb`.`cliente` (`numero_cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Veículo`
    FOREIGN KEY (`chassi_veiculo`)
    REFERENCES `mydb`.`Veiculo` (`chassi_veículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `numero_cpf_cliente` INT NOT NULL,
  `telefone` INT(9) NOT NULL,
  `ddd` INT(2) NOT NULL,
  PRIMARY KEY (`numero_cpf_cliente`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`numero_cpf_cliente`)
    REFERENCES `mydb`.`cliente` (`numero_cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
